// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCXWgetuXFgW4CK4wWHYqepTcMUQDfHbM',
    appId: '1:1059598890919:web:470cb1dba56101e6a06882',
    messagingSenderId: '1059598890919',
    projectId: 'book-swap-886c3',
    authDomain: 'book-swap-886c3.firebaseapp.com',
    storageBucket: 'book-swap-886c3.firebasestorage.app',
    measurementId: 'G-HB21ZJ8DBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrA9xJft8u9rNt4ZOaj3cXlO9RBttutgU',
    appId: '1:1059598890919:android:71fe6111ab6fc738a06882',
    messagingSenderId: '1059598890919',
    projectId: 'book-swap-886c3',
    storageBucket: 'book-swap-886c3.firebasestorage.app',
  );
}
